name: RIGOT
favicon: null
layout_spectrum: 0.27506398502737284
typography_spectrum: 0.19664021069183946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27968305558897555
  lightness: 0.6172254411503673
  saturation: 0.5028077366296202
  rhythmicContrast: 0.9756875436287373
purpose: []
