name: RIGOT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#2c2c2c'
    - '#000000'
    - '#6b6b6b'
    - '#c4c4c4'
  brandStrength: 1
  lightness: 0.6172254411503673
  saturation: 0
  rhythmicContrast: 0.9756875436287373
purpose: []
